[/]
foreground=['gdk_color_parse', '#000000']
background=['gdk_color_parse', '#ffffff']
scrollback-infinite=[true]
scrollbar-position='hidden'
use-theme-colors=[false]
use-transparent-background=[false]
custom-font=['Consolas', 11]

[palette]
# PowerShell color palette (Light)
['gdk_color_parse', '#000000']
['gdk_color_parse', '#c50f1f']
['gdk_color_parse', '#13a10e']
['gdk_color_parse', '#c19c00']
['gdk_color_parse', '#0037da']
['gdk_color_parse', '#881798']
['gdk_color_parse', '#3a96dd']
['gdk_color_parse', '#000000']
['gdk_color_parse', '#767676']
['gdk_color_parse', '#e74856']
['gdk_color_parse', '#16c60c']
['gdk_color_parse', '#f9f1a5']
['gdk_color_parse', '#3b78ff']
['gdk_color_parse', '#b4009e']
['gdk_color_parse', '#61d6d6']
['gdk_color_parse', '#ffffff']