[Scheme]
Name=PowerShell
Author=Windows 10 Theme
ColorForeground=#000000
ColorBackground=#ffffff
ColorCursor=#000000
ColorBold=#000000
ColorBoldForeground=#000000
ColorSelectionBackground=#0078d4

ColorPalette1=#000000
ColorPalette2=#c50f1f
ColorPalette3=#13a10e
ColorPalette4=#c19c00
ColorPalette5=#0037da
ColorPalette6=#881798
ColorPalette7=#3a96dd
ColorPalette8=#000000

ColorPalette9=#767676
ColorPalette10=#e74856
ColorPalette11=#16c60c
ColorPalette12=#f9f1a5
ColorPalette13=#3b78ff
ColorPalette14=#b4009e
ColorPalette15=#61d6d6
ColorPalette16=#ffffff